version: '3'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.1.4'
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    links:
      - pg
    command: bundle exec puma
    depends_on:
      - pg
  pg:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
