version: '3'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.1.4'
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - pg
    command: bundle exec puma
    depends_on:
      - pg
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
